### ISSUE TITLE
[SIS-106] Lesson Plan Module Editing

### ISSUE THREAD

**Issue by ramyzhang** [uoftblueprint/sistema#106]
> As a user of the Sistema Lesson Planner, I want to be able to move the order of my lesson plan text and activity card modules, as well as delete them.

## Technical Information

Long-press on activity card to either drag them around, or to delete them (an X icon should popup in the right corner once they're in "edit mode").
- [x] Creation of "edit mode" display
- [x] Remove activity card once deleted logic in Redux
- [x] Long-press events
- [x] Frontend display order programming

## Good Resources

[Some draggable package we might want to look into?](https://www.npmjs.com/package/react-native-draggable-flatlist)
[Long-Press for TouchableOpacity](https://reactnative.dev/docs/handling-touches#touchables)
[Figma Hi-Fidelity Wireframe](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System)
