### ISSUE TITLE
[SIS-132] Enforce lesson plan name rules

### ISSUE THREAD

**Issue by yuemily24** [uoftblueprint/sistema#132]
Enforce in the following cases:

- [ ] When you save a lesson plan, check for the following lesson plan name restrictions:
     - [ ] Name cannot match existing lesson plan
     - [ ] Name cannot contain the character ' or " (for string saving reasons) actually check if that breaks anything
- [ ] When you create a blank lesson plan, if there is an existing default date name already existing (eg. today is `Mar 13, 2023`), you must set the default name to `Mar 13, 2023 (2)`
- [x] When you duplicate a lesson plan from the options menu in Library, set the name of the copied lesson plan to `<name> (2)`, like how your computer duplicates files
- [ ] Enforce LP name character limit. Stop the user from typing beyond 75 characters when they're trying to edit the lesson plan name inside `LessonPlanHeader`.
