### ISSUE TITLE
[SIS-159] App backup in Settings page

### ISSUE THREAD

**Issue by ramyzhang** [uoftblueprint/sistema#160]
> As a user of the Sistema Lesson Planner, I want to be able to backup my data on cloud services.

## Technical Information

Some options:
- [ ] Enable [auto-backup](https://developer.android.com/guide/topics/data/autobackup) on Android devices
- [ ] iCloud backup (check [TPP commit](https://github.com/uoftblueprint/the-period-purse/commit/af301aacb462ca4b8a18e0499c74bc2742fd48e6#diff-4129552c2722e754a8dd8b6c0c240ba0222bc9f5e44020ed92c3aa3025609f73))
- [ ] Google Drive backup (requires some finicking around with authentication and a library)
- [ ] Create some kind of .csv file export with all the lesson plan information? A lot of indie apps seem to do this
