### ISSUE TITLE
[SIS-022] Blank Home Page

### ISSUE THREAD

**Issue by ramyzhang** [uoftblueprint/sistema#22]
> As a user of the Sistema Lesson Planner, I want to be able to access a page that shows me the latest Activity Cards the Sistema admins have made for us.

_Note: When you start working on this, [[SIS-029] Add initial navigation and screens](https://github.com/uoftblueprint/sistema/pull/30) should be merged. Please ping @yuemily24 if it's not._ 

## Technical Information

Inside `packages/mobile/src/home/Home.js`:
- [x] Add background colours 
- [x] Add title Recently added activity cards
- [x] Create a reusable component for a blank card UI element to the page that will later contain an image of the latest uploaded Activity Cards. (**Bonus**: try figuring out how we could "mask" or "crop" a portion of the image to fit into that nice rounded-corner box! You can test it out with Sistema activity cards.). Put the component in a new directory in `/src/home/components`
- [x] Create a scrollable container to place the card UI element in (see `ScrollView`)

Here's the designer's design for the Home page (you don't have to implement this design exactly (see checklist), this is just to get an idea of what it will look like.) The Figma node for this screen can be found [here](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=97%3A13579&t=NG0WB5xJWlil3Cpd-0) in the wireframe and will give you info like font, colour hex codes, border-radius (for rounded corners), padding, etc.

![image](https://user-images.githubusercontent.com/76456096/202871550-cd3043bb-d76f-4af5-aba5-a9f126729f95.png)

## Colours

#FFFAF5

## Good Resources

[View](https://reactnative.dev/docs/view)
[Image](https://reactnative.dev/docs/images)

- _Note:_ There are multiple ways of manipulating images in React. The default `Image` type may not be the best case for your needs. Play around with it and change types as needed.

[Stylesheet](https://reactnative.dev/docs/stylesheet)
[ScrollView](https://reactnative.dev/docs/scrollview/)
