### ISSUE TITLE
[SIS-023] Blank LP Editor Page

### ISSUE THREAD

**Issue by ramyzhang** [uoftblueprint/sistema#23]
> As a user of the Sistema Lesson Planner, I want to be able to access a page that shows me the Lesson Plan Editor page, where I can create my own Lesson Plans with Sistema teaching materials!

Style basic components for the LP Editor page! _Note: When you start working on this, [[SIS-029] Add initial navigation and screens](https://github.com/uoftblueprint/sistema/pull/30) should be merged. Please ping @yuemily24 if it's not._ 

**Technical Information:**

Inside `packages/mobile/src/editor/screens/LessonPlanEditor.js`:
- [x] Add colours
- [x] Add text headings
- [x] Implement dummy "Add ..." buttons
- [x] Implementing text box input!
- [x] Implement dummy save button
- [x] Put all of these buttons and headings in a `ScrollView` (becomes scrollable as lesson plan content is added)

By _dummy_, we mean `onPress` doesn't have to do anything. 

[Figma wireframe.](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=51%3A13021&t=IapeORhvrLZUkwRP-0) Here's the designer's design for the Lesson Plan Editor page (you don't have to implement this design _nor all the buttons and header at the top of the editor yet_, this is just to get an idea of what it will look like.) 

![Image](https://user-images.githubusercontent.com/34625981/202332425-5befa569-39cb-4c6e-ae0b-aa61fb396bf7.png)

**Colours:**

#FFFAF5
#685777

**Good Resources:**

[View](https://reactnative.dev/docs/view)
[TouchableOpacity](https://reactnative.dev/docs/touchableopacity)
[Flexbox](https://reactnative.dev/docs/flexbox) for centering
[Stylesheet](https://reactnative.dev/docs/stylesheet)
[ScrollView](https://reactnative.dev/docs/scrollview/)
[SVG docs](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md) -- for icons
1. Go to the Figma [hi-fidelity wireframe](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=42%3A12578) to export the icons as SVGs. On the right sidebar, Design > Export > SVG. 
2. See example usage of SVGs [here](https://github.com/uoftblueprint/sistema/blob/097f08271e46bce430453430d04719ecff60a771/packages/mobile/assets/HomeIcon.js). 

[TextInput](https://reactnative.dev/docs/textinput) -- for comments/textbox input
