### ISSUE TITLE
[SIS-035] Write feature breakdown [A: LESSON PLAN EDITOR] in developer contract

### ISSUE THREAD

**Issue by ramyzhang** [uoftblueprint/sistema#35]
**You can follow this sample template for the formatting of how to write this section:**

> This feature will enable the organization to match the volunteers it has on record (Salesforce)  with people that are struggling to find resources. This provides an assisted automation system  for the organization to quickly look at available volunteers and people requesting help and  perform profile matches. This feature should enable the following functionalities for users of the  application:
> 
> 1. The users, BANO administrators, should be able to login to their own dashboard and generate  customized views based on what volunteers are in their area. 
> 2. The administrators should be able to select multiple filters and sort the dashboard according to  categories such as, but not limited to, age, income level, ethnicity, and so on. 
> 3. The administrators should be given a customized matching according to their own profile. 
> 4. The volunteers who are selected to match with the clients in need should each receive email  notifications when they are matched appropriately.

**Task list:**
- [x] Write blurb about motivation and use cases of the Lesson Plan Editor feature
- [x] Cover the sections in the lesson plan editor (Warm Up, Main Lesson, Cool Down, Notes)
- [x] Cover the "add text box" and "add activity card" features
- [x] Cover the "save", "delete", and "make copy" feature
- [x] Cover the "add activity card" user flow (activity card search, preview, tagging to filter search, etc.) - see [figma](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System)
- [x] Spend extra time covering the **activity search** feature, as this is a core value proposition of the app
