### ISSUE TITLE
[SIS-036] Add activity card page

### ISSUE THREAD

**Issue by yuemily24** [uoftblueprint/sistema#36]
> As a user of the Sistema Lesson Planner, I want to be able to search for activity cards while in the lesson plan editor to add to my lesson plan. 

**Technical Information:**

Inside `packages/mobile/src/editor/screens/`:
- [ ] Create a new screen 
- [ ] Add dummy back button (icon and "Back" text shoudl be one button surrounded by a `TouchableOpacity`)
- [ ] Add title and subtitles
- [ ] Add `TagFilter` button component. Fill the screen with dummy tags for now. 
- [ ] Implement a dummy search box. You are welcome to use a package if that will make things easier. Currently, there doesn't need to be any dropdown that appears and searching doesn't have to work. 

Anything that's reusable or takes too much code, like the `TagFilter` or `Searchbar` can be put into the `components` folder inside `/editor/components`.

By _dummy_, we mean `onPress` doesn't have to do anything. 

[Figma wireframe.](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=58%3A13026&t=PVRQRJJNeXki7cqV-0) Here's the designer's design for the Add Activity Card page (you don't have to implement the follow-up page, only this one linked). Please also add more padding/margin between the components as you see fit since it's kinda squished together on the wireframe.

![Image](https://user-images.githubusercontent.com/76456096/204106259-bc59aa6a-d2fb-4297-bcc6-6b56edda595b.png)

**Good Resources:**

[View](https://reactnative.dev/docs/view)
[TouchableOpacity](https://reactnative.dev/docs/touchableopacity)
[Flexbox](https://reactnative.dev/docs/flexbox) for centering
[Stylesheet](https://reactnative.dev/docs/stylesheet)
[ScrollView](https://reactnative.dev/docs/scrollview/)
[SVG docs](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md) -- for icons
1. Go to the Figma [hi-fidelity wireframe](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=42%3A12578) to export the icons as SVGs. On the right sidebar, Design > Export > SVG. 
2. See example usage of SVGs [here](https://github.com/uoftblueprint/sistema/blob/097f08271e46bce430453430d04719ecff60a771/packages/mobile/assets/HomeIcon.js). 

[TextInput](https://reactnative.dev/docs/textinput) -- for search bar input; you're also welcome to use a package if that'll be easier, just make sure it's relatively customizable because we'll need to implement the searchbar more fully later

**Comment by yuemily24** [comment]
Update! Tags that you can include now are:
- Warm Up
- No Equipment
- Beginner
- Quick
- Scale
- Rhythm
- Note Reading
- Group Activity
