### ISSUE TITLE
[SIS-037] Write feature breakdown [B: LATEST ACTIVITY CARD DISPLAY] in developer contract

### ISSUE THREAD

**Issue by ramyzhang** [uoftblueprint/sistema#37]
**You can follow this sample template for the formatting of how to write this section:**

> This feature will enable the organization to match the volunteers it has on record (Salesforce)  with people that are struggling to find resources. This provides an assisted automation system  for the organization to quickly look at available volunteers and people requesting help and  perform profile matches. This feature should enable the following functionalities for users of the  application:
> 
> 1. The users, BANO administrators, should be able to login to their own dashboard and generate  customized views based on what volunteers are in their area. 
> 2. The administrators should be able to select multiple filters and sort the dashboard according to  categories such as, but not limited to, age, income level, ethnicity, and so on. 
> 3. The administrators should be given a customized matching according to their own profile. 
> 4. The volunteers who are selected to match with the clients in need should each receive email  notifications when they are matched appropriately.

**Task list:**
- [ ] Write blurb about motivation and use cases of the Home page and the Latest Activity Card Display feature
- [ ] Cover the latest activity card display feature, and how it refreshes weekly
- [ ] Cover the activity card preview feature
- [ ] Cover the "Add to Lesson Plan" feature for each activity card while previewing
