### ISSUE TITLE
[SIS-046] Home page info overlay

### ISSUE THREAD

**Issue by yuemily24** [uoftblueprint/sistema#46]
> As a user of the Sistema Lesson Planner, I want to be able to understand why activity cards are named that way. 

For context, according to Alex:

> Social Activity Cards have filenames with three parts:
> "Theme - Activity Type - Activity Title", for example "Listening - Knowledge - Listening Spinners"
> Theory and Musicianship Activity Cards have filenames with two parts:
> "Theme - Activity Type", for example "Harmony - Knowledge"

## Technical Information

- [ ] Add a question mark icon in ONLY the header of `Home.js`
- [ ] Clicking on the icon pulls up an overlay like in the design, with text and a button
- [ ] Ask a PL get Alex to write a blurb explaining the reasoning behind activity card naming
- [ ] For the button, you can reuse the one from this [ticket](https://github.com/uoftblueprint/sistema/issues/32). Bonus points if you're able to convert this button component into a reusable component, because it's used multiple times throughout the app. Even the purple can be made into the same component if you pass in an argument! `isPurple ? '#<purple hexcode>' : #'<blue hexcode>'` ([ternary notation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) FYI)

## Design

[Figma node](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=180%3A15386&t=uBWLplRiS9RKkpMh-0)
![image](https://user-images.githubusercontent.com/76456096/205484827-aee611b6-e43d-4a1c-a02b-9cf0244b8a28.png)

## Resources
My suggestion: make the "overlay" an entirely new screen (probably need to create a new `HomeNavigator`, see `EditorNavigator`; don't forget to change bottom tabbar component in `App.js`). That way you can add on the entire screen an onPress function to `navigation.goBack()` to the previous screen. For an example, see last year's [Period Purse screen](https://github.com/uoftblueprint/the-period-purse/blob/develop/tpp-app/src/home/pages/SelectLogOptionOverlay.js) (ask Emily if you have any questions, since I wrote the code for that part.

Your implementation should use:

[SVG docs](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md) -- for icons
1. Go to the Figma [hi-fidelity wireframe](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=42%3A12578) to export the icons as SVGs. On the right sidebar, Design > Export > SVG. 
2. See example usage of SVGs [here](https://github.com/uoftblueprint/sistema/blob/097f08271e46bce430453430d04719ecff60a771/packages/mobile/assets/HomeIcon.js). 

[TouchableOpacity](https://reactnative.dev/docs/touchableopacity)
