### ISSUE TITLE
[SIS-048] Preview featured activity cards from the home page

### ISSUE THREAD

**Issue by yuemily24** [uoftblueprint/sistema#48]
> As a user of the Sistema Lesson Planner, I want to be able to view recently added activity cards on the home page. 

This is a 2-part ticket, a companion piece to [[SIS-049] Get featured activity cards on home page](https://github.com/uoftblueprint/sistema/issues/49). This is the front-end portion of it. I recommend starting with this first, but it's up to you. 

For context, each week Alex uploads 2-8 new "featured" activity cards he wants teachers to use. These activity cards will often share a "theme". See how activity cards are named:

> Social Activity Cards have filenames with three parts:
> "Theme - Activity Type - Activity Title", for example "Listening - Knowledge - Listening Spinners"
> Theory and Musicianship Activity Cards have filenames with two parts:
> "Theme - Activity Type", for example "Harmony - Knowledge"

Although he sends out an email to all the teachers explaining the theme and pedagogy, we want teachers to be able to see it front and center on the home screen of the app as well--for easy viewing and as a reminder to use them. 

## Technical Information

- [x] Add a subtitle and dummy refresh icon for last updated
- [x] Make the activity card component accurate to the design (add an element for the title; ellipse any long titles)
- [x] When a user taps on the  activity card component, slide in a new screen previewing the activity card full screen. 

- You will have to add a new `HomeNavigator.js` so you can add this screen as a new stack, see `EditorNavigator.js`. Make sure to update the tabbar component in `App.js` to this navigator. Think about what props you'll need to pass forward. 
- Add a title
- Add a back button. See [RN navigation](https://reactnavigation.org/docs/getting-started/) -> `navigation.goBack()`
- Add a dummy "Add to lesson plan" button. Talk to your peers, because this button style has been implemented a bunch of times in the app.
      
## Design

[Figma](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=128%3A15606&t=uBWLplRiS9RKkpMh-0)

![image](https://user-images.githubusercontent.com/76456096/205485740-b1400991-5603-4c5f-ad9d-82429930add4.png)

Ignore the arrow buttons surrounding the image!
![image](https://user-images.githubusercontent.com/76456096/205485809-e854d7e0-8e3d-49f9-9d69-13c5c701a44f.png)

## Resources

[RN Navigation](https://reactnavigation.org/docs/getting-started/)
