### ISSUE TITLE
[SIS-050] Add text module to LP

### ISSUE THREAD

**Issue by yuemily24** [uoftblueprint/sistema#50]
> As a user of the Sistema Lesson Planner, I want to be able to add a text module to my lesson plan. 

## Technical Information

- [x] Tapping on any "Insert Text" button should pull up a textbox above the buttons, allowing a user to type. The textbox should expand in length as the user types more. 
- [x] Tapping anywhere outside the textbox means the user is done typing (I believe you can utilize if the textbox is in focus or not). If the textbox is empty, close it up. If it has text, move it to the bottom of the section. 
- [x] I should be able to keep adding text modules and they'll keep moving and stacking at the bottom of the section. 
- [ ] Store all the text in the lesson plan in an array or map state on `LessonPlanEditor`. Think about how might we combine these states into a single string? This is going to be the beginnings of what we store on the lesson plan on the backend. For now, these states doesn't have to persist (meaning if you exit outside this screen, the inserted text modules will disappear). 

**EXTRA:**
Since last time's PR didnt have responsive styling, please go back into all of the previous LP Editor classes and make all your CSS responsive in this ticket!
You can do this by either changing all your hard-coded pixel values to percentages, or by using Flexbox. See [this blog post](https://medium.com/simform-engineering/create-responsive-design-in-react-native-f84522a44365) for a crash course on how to do this!
- [ ] Make styling on all LP Editor components responsive

## Design

[Figma](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=58%3A12881&t=uBWLplRiS9RKkpMh-0)

![image](https://user-images.githubusercontent.com/76456096/205488340-d9bd4032-80f9-48fe-ae22-fc705a5a16ca.png)
![image](https://user-images.githubusercontent.com/76456096/205488349-d39fd356-1fdf-4c4d-af54-49fd26432cb9.png)

## Resources

Check out this example code [here](https://github.com/uoftblueprint/the-period-purse/blob/develop/tpp-app/src/info/Info.js):
```javascript
const optionData = [
    {
        name: "Export Lesson Plan",
        image: <SaveIcon/>,
        screen: STACK_SCREENS.EXPORT_LESSON_PLAN
    },
    {
        name: "Add to Favourites",
        image: <HeartIcon/>,
        screen: STACK_SCREENS.ADD_TO_FAVOURITES
    },
    ...
]
```
And then we can do:
```javascript
  <View style={styles.containerRow}>
      {optionData.map((option, i) => { return (
          <LessonPlanOption
              key={i}
              name={option.name}
              image={option.image}
              onPress={() => navigation.navigate(option.screen)}
          />
      )})}
  </View>
```
This will let you dynamically render components (text modules) based on an array (which we can use a state for).
