### ISSUE TITLE
[SIS-051] Blank Library Page

### ISSUE THREAD

**Issue by yuemily24** [uoftblueprint/sistema#51]
> As a user of the Sistema Lesson Planner, I want to be able to see a library of my lesson plans.

## Technical Information

Inside `/src/library/Library.js`:
- [x] Add background colours 
- [x] Add title "Lesson Plans" and a dummy menu button on the right (use flexbox to position these two)
- [x] Create a reusable component for a lesson plan button. Expand the button height if the title is super long, but don't push over the icons. Put the component in a new directory in `/src/library/components`
     - [x] Add dummy heart and menu button icons within this
- [x] Create a scrollable container to place the LP UI elements in (see `ScrollView`)

By dummy, I mean that `onPress` doesn't have to do anything right now. 

## Design

The Figma node for this screen can be found [here](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=278%3A16162&t=uBWLplRiS9RKkpMh-0) in the wireframe and will give you info like font, colour hex codes, border-radius (for rounded corners), padding, etc.

![image](https://user-images.githubusercontent.com/76456096/205489238-ccce60d6-e2b3-4bde-90b7-e9a72e995dda.png)

## Good Resources

[View](https://reactnative.dev/docs/view)
[Stylesheet](https://reactnative.dev/docs/stylesheet)
[ScrollView](https://reactnative.dev/docs/scrollview/)
[TouchableOpacity](https://reactnative.dev/docs/touchableopacity)
[Flexbox](https://reactnative.dev/docs/flexbox) for centering
[SVG docs](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md) -- for icons
1. Go to the Figma [hi-fidelity wireframe](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=42%3A12578) to export the icons as SVGs. On the right sidebar, Design > Export > SVG. 
2. See example usage of SVGs [here](https://github.com/uoftblueprint/sistema/blob/097f08271e46bce430453430d04719ecff60a771/packages/mobile/assets/HomeIcon.js). 
Although, check in with this [ticket](https://github.com/uoftblueprint/sistema/issues/47) first to see if a new, easier package can be used.
