### ISSUE TITLE
[SIS-052] Edit lesson plan name

### ISSUE THREAD

**Issue by yuemily24** [uoftblueprint/sistema#52]
> As a user of the Sistema Lesson Planner, I want to be able to edit my lesson plan (LP) name in the LP editor. 

_Jan 24 Update:_
- Default LP name: “Date”: Lesson Plan
- Ex. “Jan 19, 2023: Lesson Plan”
- Ex. “Jan 19, 2023: Lesson Plan (1)” ← if making another lesson plan on the same day

## Technical Information

- [ ] Create a react state to hold the LP name in 
- [ ] Convert the title into a textbox that the user can edit 
- [ ] Editing the name will change the react state
- [ ] Decide on a character limit for the LP name and enforce it! A user won't be able to type in the textbox past that limit. 
- [ ] The name should ellipse if it's cut off by the right hand side icons (but not when the user is editing it)

## Design

[Figma](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=51%3A13021&t=uBWLplRiS9RKkpMh-0)

![image](https://user-images.githubusercontent.com/76456096/205489977-5d1f32e7-6afe-4bba-a1fe-c3149dc797f0.png)

## Resources
[TextInput](https://reactnative.dev/docs/textinput)
[Stylesheet](https://reactnative.dev/docs/stylesheet)
