### ISSUE TITLE
[SIS-053] Lesson plan options menu

### ISSUE THREAD

**Issue by yuemily24** [uoftblueprint/sistema#53]
> As a user of the Sistema Lesson Planner, I want to pull up an options menu to see what I can do with my lesson plan (LP). 

## Technical Information

This menu is used both in the LP Editor and Library, with the exception of the middle button and menu title. Make it a reusable component between the two. 

Tapping outside of the menu or on the 'X' should close it (see Resources).

You'll be blocked by [[SIS-051]](https://github.com/uoftblueprint/sistema/issues/51) from adding it to the Library page. 

## Design

The button borders are kinda thick for the inner ones because they're doubled up. Try to avoid that. 

### LP editor
[Figma](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=138%3A14431&t=uBWLplRiS9RKkpMh-0)

- [ ] Inside LP editor: tapping on "Add to Favourites" should change the icon and text, and a pop up "Lesson plan added to favourites" should briefly appear. Tapping on it again should change it back and a different pop up should appear. 
- [ ] Other dummy buttons (`onPress `does nothing)

![image](https://user-images.githubusercontent.com/76456096/205490571-03cbb274-2655-45c8-9146-81882435f197.png)
![image](https://user-images.githubusercontent.com/76456096/205490802-3c3e98cd-48b8-4d31-ad80-a4974c6507ec.png)
![image](https://user-images.githubusercontent.com/76456096/205490822-8b41f8f4-6f93-4b1c-af8b-bd11c70844ec.png)

### Library
[Figma](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=280%3A15467&t=uBWLplRiS9RKkpMh-0)

- [ ] Other dummy buttons (`onPress` does nothing)

![image](https://user-images.githubusercontent.com/76456096/205490832-7ff695c0-fb46-4a96-9de5-838030b978cf.png)

## Resources
[TouchableOpacity](https://reactnative.dev/docs/touchableopacity)
[Flexbox](https://reactnative.dev/docs/flexbox) for centering
[SVG docs](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md) -- for icons
1. Go to the Figma [hi-fidelity wireframe](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=42%3A12578) to export the icons as SVGs. On the right sidebar, Design > Export > SVG. 
2. See example usage of SVGs [here](https://github.com/uoftblueprint/sistema/blob/097f08271e46bce430453430d04719ecff60a771/packages/mobile/assets/HomeIcon.js). 
Although, check in with this [ticket](https://github.com/uoftblueprint/sistema/issues/47) first to see if a new, easier package can be used. 

### Overlay tapping to close
Make the "overlay" an entirely new screen in `EditorNavigator`. That way you can add on the entire screen an onPress function to `navigation.goBack()` to the previous screen. For an example, see last year's [Period Purse screen](https://github.com/uoftblueprint/the-period-purse/blob/develop/tpp-app/src/home/pages/SelectLogOptionOverlay.js) (ask Emily if you have any questions, since I wrote the code for that part.
OR Dig around for some packages that might help!

### Dynamic rendering (optional)

You may or may not want to use this. Up to you. Check out this example code [here](https://github.com/uoftblueprint/the-period-purse/blob/develop/tpp-app/src/info/Info.js):
```javascript
const optionData = [
    {
        name: "Export Lesson Plan",
        image: <SaveIcon/>,
        screen: STACK_SCREENS.EXPORT_LESSON_PLAN
    },
    {
        name: "Add to Favourites",
        image: <HeartIcon/>,
        screen: STACK_SCREENS.ADD_TO_FAVOURITES
    },
    ...
]
```
And then we can do:
```javascript
  <View style={styles.containerRow}>
      {optionData.map((option, i) => { return (
          <LessonPlanOption
              key={i}
              name={option.name}
              image={option.image}
              onPress={() => navigation.navigate(option.screen)}
          />
      )})}
  </View>
```
This will let you dynamically render components (text modules) based on an array.

**Comment by helenaglow** [comment]
I believe the merge conflict is because I changed the sistemaLogo.svg name conflict in Header.
