### ISSUE TITLE
[SIS-083] Lesson Plan Editor backend

### ISSUE THREAD

**Issue by ramyzhang** [uoftblueprint/sistema#83]
> As a user of the Sistema Lesson Planner, I want to be able to create, edit and save new lesson plans!

## Technical Information

**Endpoints to implement:**
`saveLessonPlan` --> this is the meatier endpoint, ideally one person should take responsibility over this one!
`getLessonPlan` --> this can be grouped with deleteLessonPlan for the other person!
`deleteLessonPlan`

You will find these endpoints inside `LessonPlanService.js` under `/services/`. You can implement them following the example from the `deleteLessonPlan` endpoint; specifically, make sure that you're *not* calling the RNFS library directly in the function, but rather the required function from `Local.js` that will make the call to the library for you. Use the path constant from `constants.js` if you need access to a directory path constant as defined in the [documentation](https://github.com/itinance/react-native-fs#constants)!

Since you'll be working on the same file, `LessonPlanService.js` in tandem with @helenaglow, make sure to discuss with her for this ticket! We suggest starting a DM group chat together as you're starting your ticket. _Specifically, please discuss with each other how to implement the LessonPlan object specification in `/models/` because you'll be using it a lot in the service file!_

Questions on implementation? Missing functions in Local.js for RNFS calls that you need? *DM the PLs the second you see the issue!*

## Local Storage Structure

In RNFS.DocumentDirectoryPath, establish 2 folders: `Default` and `Favourited`. Lesson Plans when first created should all go into the Default folder, and each lesson plan should create its own directory. 

> **Example:** `Default/LESSON_PLAN_NAME/`

In each lesson plan's directory, you'll have the `.json` file that details its contents, as well as its corresponding activity cards that the user attached to it. 

> For this ticket, we will only require backend implementation for **TEXT-ONLY LESSON PLANS**. You can disregard implementing saving activity cards (i.e. images) in the lesson plan folders, but please do _think about_ how you might write your code right now to accommodate for activity cards in the future!

When a lesson plan is favourited, move its directory into the `Favourited` folder. `Favourited` lesson plans are essentially pinned lesson plans, and should always be _displayed first_ in the UI, unless the user is sorting their lesson plans by name, or date, or whatever.

Things to consider and discuss with your ticket group (aka @helenaglow):
- How should we initialize the two directory paths `Default` and `Favourited`? Does RNFS automatically do it when we write to it with a path? Try it!
- What's the best way to return errors? How do you write more informative error messages?
- Are all moveFile() and related operations done recursively (a.k.a do all the contents of the directory move too?)

### saveLessonPlan
**Description:** 
Given a LessonPlan object, store a lesson plan on the app's local backend in the `RNFS.DocumentDirectoryPath + "/Default/"` directory. Should create a directory named `LESSON_NAME` and a corresponding .json file to be written into the directory. (Hint: stringify the lesson plan object!)

**Discussion:** 
Check the [wiki](https://github.com/uoftblueprint/sistema/wiki/Lesson-Plan-API) for more info, as well as the [Endpoint Reference](https://docs.google.com/document/d/1JdqTkQoUPN7ov9fGmf_vruavwfDfUzUdNY5I9AccnKQ/edit)!

### getLessonPlan
**Description:** 
Given a lesson plan's name, search through the `RNFS.DocumentDirectoryPath + "/Default/"` and `RNFS.DocumentDirectoryPath + "/Favourited/"` directories to return the LessonPlan object.

**Discussion:** 
Check the [wiki](https://github.com/uoftblueprint/sistema/wiki/Lesson-Plan-API) for more info, as well as the [Endpoint Reference](https://docs.google.com/document/d/1JdqTkQoUPN7ov9fGmf_vruavwfDfUzUdNY5I9AccnKQ/edit)! 
- Note that the corresponding Local.js function for `RNFS.exists()` requires a path as well, so make sure to configure that within your function!

### deleteLessonPlan
**Description:** 
Given a lesson plan's name, search through the `RNFS.DocumentDirectoryPath + "/Default/"` and `RNFS.DocumentDirectoryPath + "/Favourited/"` directories to recursively delete its directory. 

**Discussion:** 
Check the [wiki](https://github.com/uoftblueprint/sistema/wiki/Lesson-Plan-API) for more info, as well as the [Endpoint Reference](https://docs.google.com/document/d/1JdqTkQoUPN7ov9fGmf_vruavwfDfUzUdNY5I9AccnKQ/edit)! 

## Resources

Definitely think out your strategy first before writing any code. This ticket is in general very collaborative. Discuss with the Lesson Plan group: @Lemiex & @kurtislaw & @helenaglow 
[Official RNFS Documentation](https://github.com/itinance/react-native-fs)
[Testing RNFS](https://github.com/uoftblueprint/sistema/wiki/Testing-Local-Storage-Calls)

**Comment by yuemily24** [comment]
@Lemiex & @kurtislaw part 2:

- Discuss grabbing lesson plan object from `getLessonPlan` and puting it in redux store
    - see TPP `useEffect` [here](https://github.com/uoftblueprint/the-period-purse/blob/b128960545b575618607a84c99f1f23f277c2562/tpp-app/src/home/pages/LogSymptomsScreen.js#L151-L171) to fetch data when component first mounts
- State of lesson plan in Redux should be user's "most up-to-date", editing modules should edit the redux store call 
- Press save button should call `saveLessonPlan`, which sends current lesson plan object from Redux state into RNFS local storage like in TPP [here](https://github.com/uoftblueprint/the-period-purse/blob/b128960545b575618607a84c99f1f23f277c2562/tpp-app/src/home/pages/LogSymptomsScreen.js#L208-L241)
- Implement `deleteLessonPlan` [flow](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=584-17173&t=hYIjTSdzDwG3joB8-0)

**Comment by Lemiex** [comment]
Also adding images to the lesson plan

**Comment by yuemily24** [comment]
Related PR [[SIS-106] Lesson Plan Module Editing](https://github.com/uoftblueprint/sistema/pull/120)

## Checklist for Sarah & Kurtis moving forward

- [ ] Address TODOs in `src\editor` and `lessonPlanSlice.js`. Ctrl+shift+f to find all the TODOs I left for you. Don't worry about [SIS-118].
- [ ] Once you're done, delete LessonPlanEditor and any unused components and functions
- [ ] `getLessonPlan` will go inside `LessonSectionDraggable`. See TODO I left you.  
- [ ] Save button inside `LessonPlanEditorV2` should call `saveLessonPlan`, which sends current LP from Redux into RNFS local storage like in TPP [here](https://github.com/uoftblueprint/the-period-purse/blob/b128960545b575618607a84c99f1f23f277c2562/tpp-app/src/home/pages/LogSymptomsScreen.js#L208-L241). Like TPP, make sure you're adding a `isSubmitting` component state to disable any accidental user changes while it's saving. Move back to Library screen once succeeded.
- [ ] Add support for activity cards (adding images to LP). Activity Cards only need the "Delete" option on the menu. 
- [ ] Implement deleteLessonPlan [flow](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=584-17173&t=hYIjTSdzDwG3joB8-0)
